### ISSUE TITLE
Mount data volume on host

### ISSUE THREAD

**Issue by shibinv** [nazar-pc/docker-webserver#24]
Is there a way to mount the data volume on the host while its running? I was trying to use for development so files can be saved and it would be live.

**Comment by nazar-pc** [comment]
Sure, but not while its running, but rather before. In current versions of images you only need to mount single data volume into directory `/data` (SSH image also uses `/etc/ssh`, but you probably don't need it for development).

Just look at Dockerfile of each image, for instance, PHP: https://github.com/nazar-pc/docker-webserver/blob/f77c47f2f71498d4e7a33dbe2bcbd029701a66bc/Dockerfile-php-fpm#L27

You can create volume for `data` image and just use it everywhere like before. Can be something like this:
```yml
version: '2'
services:
  data:
    image: nazarpc/webserver:data
    volumes:
      - ./data:/data
...
```

You can then destroy everything, add another volume to `docker-compose.yml` that will contain your PHP sources like following and start everything again:
```yml
version: '2'
services:
  data:
    image: nazarpc/webserver:data
    volumes:
      - ./data:/data
      - /path/to/your/website/on/host:/data/nginx/www
...
```

2 steps are needed for Nginx container to initialize on the first run. After first run you can also customize its configuration in `./data/nginx/config` directory.
