### ISSUE TITLE
PhpMyAdmin container with Consul support

### ISSUE THREAD

**Issue by nazar-pc** [nazar-pc/docker-webserver#4]
PhpMyAdmin image based on `nazarpc/phpmyadmin` with Consul support for DNS resolving and load balancing support.

**Comment by nazar-pc** [comment]
Implemented in 861bb28.
Example of configuration:

``` yml
data:
  image: nazarpc/webserver:data
consul:
  image: nazarpc/webserver:consul
  environment:
    CONSUL_SERVICE: consul
    SERVICES: mariadb:mysql
mariadb:
  image: nazarpc/webserver:mariadb-next
  environment:
    CONSUL_SERVICE: consul
    SERVICE_NAME: mariadb
  volumes_from:
    - data
phpmyadmin:
  image: nazarpc/webserver:phpmyadmin
  ports:
    - 127.0.0.1:1234:80
```

Will also work with load balancing
