### ISSUE TITLE
CephFS image

### ISSUE THREAD

**Issue by nazar-pc** [nazar-pc/docker-webserver#5]
Well, without really scalable underlaying storage these images are not trully scalable in general sense.
So, there should be combined client-server (with possibility to use any or both) GlusterFS image that would span across physical servers and thus providing complete scalability of the whole stack.
Unfortunately, didn't found any image suitable out of the box or even such that can be taken as the basis for target image.
Zero-configuration is expected as always:)

**Comment by nazar-pc** [comment]
Thanks, @vipconsult, for advice about lsyncd, I'll check it as well!
If you have any comments - it is better to write in this repository, since they were not related to MariaDB.

**Comment by nazar-pc** [comment]
Unfortunately, lsyncd is not suitable as general purpose solution here, still stick to GlusterFS.

**Comment by nazar-pc** [comment]
GlusterFS is  extremely non-flexible, switching to CephFS instead.
Have some early progress, nothing to show yet.

**Comment by nazar-pc** [comment]
Ceph image added and CephFS clients added to necessary images as per 948629f
No docs yet, also rules to place Consul and Ceph containers within cluster should be made in order to avoid loosing data (partially depends on https://github.com/docker/compose/issues/2559, https://github.com/docker/docker/issues/18624, https://github.com/docker/compose/issues/2451).

Example how to use it (within single host, will not survive recreation because of https://github.com/docker/compose/issues/2423):

``` yml
# docker-compose.yml
consul:
  image: nazarpc/webserver:consul

ceph-mon:
  image: nazarpc/webserver:ceph
  command: mon
  restart: always

ceph-osd:
  image: nazarpc/webserver:ceph
  command: osd
  restart: always

ceph-mds:
  image: nazarpc/webserver:ceph
  command: mds
  restart: always

nginx:
  image: nazarpc/webserver:nginx
  environment:
    CEPHFS_MOUNT: 1
# In order to access FUSE
  devices:
    - /dev/fuse:/dev/fuse
# In order to mount CephFS
  cap_add:
    - SYS_ADMIN

mariadb:
  image: nazarpc/webserver:mariadb
  environment:
    CEPHFS_MOUNT: 1
# In order to access FUSE
  devices:
    - /dev/fuse:/dev/fuse
# In order to mount CephFS
  cap_add:
    - SYS_ADMIN
```

``` bash
docker-compose --x-networking up -d
docker-compose --x-networking scale ceph-mon=3 ceph-mds=3 ceph-osd=5 nginx=3 mariadb=2
```

In order to start using CephFS you'll need more than one Ceph OSD.

**Comment by nazar-pc** [comment]
Works fine with config like this:
```yml
...
  nginx:
    image: nazarpc/webserver:nginx
    environment:
      CEPHFS_MOUNT: 1
# In order to access FUSE
    devices:
      - /dev/fuse
# Because https://github.com/docker/docker/issues/16429
    security_opt:
      - "apparmor:unconfined"
# In order to mount CephFS
    cap_add:
      - SYS_ADMIN
...
```
